_target_: src.utils.logging.get_neptune_logger

logger: neptune

log_db: manual_runs
tag_attrs: 
  - ${data.dataset}
  - ${model.model_type}
  - ${model.arch}
name: test
offline: False
project_name: INK-HITL/free-text-utility